# McNemar test results

This notebook displays the newest complete McNemar tests across all ranking paradigms. The input CSV is generated by `mcnemar_all.py`.

In [10]:
from pathlib import Path
import pandas as pd

csv_path = Path('Results/mcnemar_all.csv')
if not csv_path.exists():
    csv_path = Path('mcnemar_all.csv')
results = pd.read_csv(csv_path)
# Exclude controlled reasoning/thinking-effort ablation runs for now.
if 'source' in results.columns:
    ablation_mask = results['source'].str.contains('ablation|reasoning|thinking|effort', case=False, na=False)
    results = results.loc[~ablation_mask].copy()
results.head()

,model,dataset,paradigm,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction,source
0,Llama3-70B,TREC-DL-2019,pairwise,dch,defense,4096,2040,26,277,1753,3.662764e-54,-53.436191,3.699391e-52,True,improvement,LLM_prompt_attack/outputs/Llama3-70B_dch_defen...
1,Llama3-70B,TREC-DL-2019,pairwise,doh,standard,4096,55,2012,2029,0,8.012801e-01,-0.096216,1.000000e+00,False,improvement,LLM_prompt_attack/outputs/Llama3-70B_doh_20260...
2,Llama3-70B,TREC-DL-2020,pairwise,qi,defense_qi,4096,2041,0,0,2055,1.000000e+00,0.000000,1.000000e+00,False,tie,LLM_prompt_attack/outputs/Llama3-70B_qi_pairwi...
3,Llama3-8B,TREC-DL-2019,pointwise,qi,defense_qi,4096,2017,304,286,1489,4.840346e-01,-0.315124,1.000000e+00,False,degradation,LLM_prompt_attack/outputs/Llama3-8B_pointwise_...
4,Llama3-8B,TREC-DL-2019,pointwise,qi,standard,4096,2250,441,276,1129,7.690516e-10,-9.114045,4.921930e-08,True,degradation,LLM_prompt_attack/outputs/Llama3-8B_pointwise_...

## Full McNemar contingency table

`b` is clean-correct/attack-wrong; `c` is clean-wrong/attack-correct. A positive degradation direction means `b > c`.

In [11]:
columns = [
    'model', 'dataset', 'paradigm', 'attack', 'prompt', 'paired',
    'both_correct', 'clean_correct_attack_wrong',
    'clean_wrong_attack_correct', 'both_wrong',
    'p_value_exact', 'p_value_exact_log10', 'p_value_holm',
    'significant_holm_0.05', 'direction'
]
display_df = results[[c for c in columns if c in results.columns]].copy()
display_df

,model,dataset,paradigm,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Llama3-70B,TREC-DL-2019,pairwise,dch,defense,4096,2040,26,277,1753,3.662764e-54,-53.436191,3.699391e-52,True,improvement
1,Llama3-70B,TREC-DL-2019,pairwise,doh,standard,4096,55,2012,2029,0,8.012801e-01,-0.096216,1.000000e+00,False,improvement
2,Llama3-70B,TREC-DL-2020,pairwise,qi,defense_qi,4096,2041,0,0,2055,1.000000e+00,0.000000,1.000000e+00,False,tie
3,Llama3-8B,TREC-DL-2019,pointwise,qi,defense_qi,4096,2017,304,286,1489,4.840346e-01,-0.315124,1.000000e+00,False,degradation
4,Llama3-8B,TREC-DL-2019,pointwise,qi,standard,4096,2250,441,276,1129,7.690516e-10,-9.114045,4.921930e-08,True,degradation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Llama3-70B,TREC-DL-2020,pointwise,qi,standard,4096,3309,154,228,405,1.798929e-04,-3.744986,8.814750e-03,True,improvement
131,Qwen3-32B,TREC-DL-2019,pointwise,qi,defense_qi,3565,2742,225,32,566,6.686837e-37,-36.174779,6.352495e-35,True,degradation
132,Qwen3-32B,TREC-DL-2019,pointwise,qi,standard,4034,3159,392,71,412,7.546652e-55,-54.122246,7.697585e-53,True,degradation
133,Qwen3-32B,TREC-DL-2020,pointwise,qi,defense_qi,3580,2922,116,37,505,1.092713e-10,-9.961494,7.211905e-09,True,degradation
134,Qwen3-32B,TREC-DL-2020,pointwise,qi,standard,4048,3479,183,55,331,2.966420e-17,-16.527767,2.254479e-15,True,degradation

## Split tables by dataset and ranking paradigm

In [12]:
table_columns = [
    'model', 'attack', 'prompt', 'paired', 'both_correct',
    'clean_correct_attack_wrong', 'clean_wrong_attack_correct',
    'both_wrong', 'p_value_exact_log10', 'p_value_holm',
    'significant_holm_0.05', 'direction'
]
for (dataset, paradigm), subset in results.groupby(['dataset', 'paradigm'], sort=True):
    print(f'{dataset} — {paradigm.title()}')
    display(subset[[c for c in table_columns if c in subset.columns]].reset_index(drop=True))

TREC-DL-2019 — Pairwise

,model,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Llama3-70B,dch,defense,4096,2040,26,277,1753,-53.436191,3.699391e-52,True,improvement
1,Llama3-70B,doh,standard,4096,55,2012,2029,0,-0.096216,1.000000e+00,False,improvement
2,Qwen3-4B,key_injection,defense,4096,3113,323,191,469,-8.202333,3.828218e-07,True,degradation
3,Qwen3-4B,key_injection,standard,4096,2156,190,257,1493,-2.752747,7.775100e-02,False,improvement
4,Llama3-70B,qi,defense_qi,4096,2066,0,0,2030,0.000000,1.000000e+00,False,tie
5,Llama3-70B,qi,standard,4096,2066,2,0,2028,-0.301030,1.000000e+00,False,degradation
6,Llama3-8B,dch_back_defense_n4096,unknown,4096,1396,1834,698,168,-115.965775,1.233474e-114,True,degradation
7,Llama3-8B,dch_back_standard_n16,unknown,16,1,13,1,1,-2.737299,7.873535e-02,False,degradation
8,Llama3-8B,dch_back_standard_n4096,unknown,4096,434,3239,379,44,-1088.825494,0.000000e+00,True,degradation
9,Llama3-8B,qi,filter_qi,4096,3582,45,49,420,-0.120796,1.000000e+00,False,improvement
10,Llama3-8B,qi,standard,4096,3577,47,139,333,-11.026855,6.392246e-10,True,improvement
11,Qwen3-32B,qi_back,defense,4096,2756,543,167,630,-46.520649,3.015443e-45,True,degradation
12,Qwen3-32B,qi_back,defense_qi,4096,3705,157,95,139,-3.946347,5.770633e-03,True,degradation
13,Qwen3-32B,qi_back,standard,4096,2132,1374,130,460,-261.667362,2.796282e-260,True,degradation
14,Qwen3-4B,qi_back,defense,4096,3270,163,188,475,-0.698717,1.000000e+00,False,improvement
15,Llama3-70B,key_injection,defense,4096,2066,0,0,2030,0.000000,1.000000e+00,False,tie
16,GPT-OSS-20B,key_injection,defense,4096,3317,491,226,62,-22.708757,1.681671e-21,True,degradation
17,Llama-3-8B,key_injection,defense,4096,3377,380,142,197,-25.360827,3.877604e-24,True,degradation
18,Qwen3-32B,key_injection,defense,4096,2935,367,313,481,-1.376457,1.000000e+00,False,degradation
19,GPT-OSS-20B,key_injection,unknown,4096,3293,518,215,70,-28.989043,9.229947e-28,True,degradation
20,Llama3-70B,key_injection,unknown,4096,2067,0,1,2028,0.000000,1.000000e+00,False,improvement
21,Qwen3-32B,key_injection,unknown,4096,3079,409,283,325,-5.722331,1.099251e-04,True,degradation

TREC-DL-2019 — Pointwise

,model,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Llama3-8B,qi,defense_qi,4096,2017,304,286,1489,-0.315124,1.000000e+00,False,degradation
1,Llama3-8B,qi,standard,4096,2250,441,276,1129,-9.114045,4.921930e-08,True,degradation
2,Llama3-8B,sd,defense,4096,1876,592,26,1602,-139.987590,1.203916e-138,True,degradation
3,Llama3-8B,sd,standard,4096,1017,1674,0,1405,-503.623183,0.000000e+00,True,degradation
4,Llama3-8B,so,defense,4096,2144,324,111,1517,-24.529665,2.569532e-23,True,degradation
5,Llama3-8B,so,standard,4096,641,2050,8,1397,-619.218701,0.000000e+00,True,degradation
6,Qwen3-32B,sd,defense,3951,3641,9,93,208,-18.000976,7.782495e-17,True,improvement
7,Qwen3-32B,sd,standard,4092,527,3085,2,478,-928.978567,0.000000e+00,True,degradation
8,Qwen3-32B,so,defense,4086,3462,275,7,342,-71.161594,7.168686e-70,True,degradation
9,Qwen3-32B,so,standard,4094,2674,931,11,478,-258.176123,8.599377e-257,True,degradation
10,Qwen3-4B,sd,defense,316,41,5,1,269,-0.660052,1.000000e+00,False,degradation
11,Qwen3-4B,sd,standard,916,224,287,0,405,-86.094579,8.766934e-85,True,degradation
12,Qwen3-4B,so,defense,323,46,7,4,266,-0.260564,1.000000e+00,False,degradation
13,Qwen3-4B,so,standard,916,418,93,2,403,-24.637760,2.026391e-23,True,degradation
14,GPT-OSS-20B,key_injection,defense,4096,2894,824,58,320,-173.542027,3.444720e-172,True,degradation
15,GPT-OSS-20B,key_injection,standard,4096,2838,894,66,298,-185.553746,3.436839e-184,True,degradation
16,Llama-3-8B,key_injection,standard,4096,948,1754,11,1383,-531.016912,0.000000e+00,True,degradation
17,Llama3-70B,key_injection,defense,4096,1602,1887,20,587,-573.763172,0.000000e+00,True,degradation
18,Llama3-70B,key_injection,standard,4096,1280,2051,6,759,-618.917671,0.000000e+00,True,degradation
19,Qwen3-32B,key_injection,defense,4078,2755,979,11,333,-272.387150,5.412820e-271,True,degradation
20,Qwen3-32B,key_injection,standard,4089,2061,1540,19,469,-469.004733,0.000000e+00,True,degradation
21,Qwen3-4B,key_injection,defense,234,12,5,0,217,-1.204120,1.000000e+00,False,degradation
22,Qwen3-4B,key_injection,standard,798,339,96,13,350,-16.080742,6.227584e-15,True,degradation
23,Llama-3-8B,sd,defense,4091,1917,549,33,1592,-120.969384,1.233997e-119,True,degradation
24,Llama-3-8B,sd,standard,4087,1024,1672,1,1390,-503.322153,0.000000e+00,True,degradation
25,Llama-3-8B,so,defense,4085,2212,249,132,1492,-8.675532,1.308760e-07,True,degradation
26,Llama-3-8B,so,standard,4090,736,1961,9,1384,-592.728061,0.000000e+00,True,degradation
27,Llama3-70B,sd,defense,4096,3477,14,261,344,-59.394346,4.154240e-58,True,improvement
28,Llama3-70B,sd,standard,4096,21,3312,0,763,-996.710316,0.000000e+00,True,degradation
29,Llama3-70B,so,defense,4096,3416,70,120,490,-3.453037,1.656003e-02,True,improvement
30,Llama3-70B,so,standard,578,80,441,1,56,-130.107824,9.049688e-129,True,degradation
31,GPT-OSS-20B,qi,defense_qi,4068,3528,122,59,359,-5.485898,1.861989e-04,True,degradation
32,GPT-OSS-20B,qi,standard,4083,3625,101,76,281,-1.149120,1.000000e+00,False,degradation
33,Llama-3-8B,qi,defense_qi,4096,1857,276,370,1593,-3.606585,1.187561e-02,True,improvement
34,Llama-3-8B,qi,standard,4096,2303,398,297,1098,-3.838407,7.253761e-03,True,degradation
35,Llama3-70B,qi,defense_qi,4096,3182,240,172,502,-3.026295,4.235621e-02,True,degradation
36,Llama3-70B,qi,standard,4096,3064,272,250,510,-0.446078,1.000000e+00,False,degradation
37,Qwen3-32B,qi,defense_qi,3565,2742,225,32,566,-36.174779,6.352495e-35,True,degradation
38,Qwen3-32B,qi,standard,4034,3159,392,71,412,-54.122246,7.697585e-53,True,degradation

TREC-DL-2019 — Setwise

,model,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Qwen3-32B,qi_back,defense,3706,2428,178,129,971,-2.217351,2.364362e-01,False,degradation
1,Qwen3-32B,key_injection,defense,3706,2344,267,144,951,-8.872052,8.458398e-08,True,degradation

TREC-DL-2020 — Pairwise

,model,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Llama3-70B,qi,defense_qi,4096,2041,0,0,2055,0.000000,1.000000e+00,False,tie
1,Llama3-8B,qi,defense_qi,4096,2358,42,244,1452,-35.068399,8.030240e-34,True,improvement
2,Qwen3-4B,key_injection,defense,4096,2976,253,205,662,-1.553298,1.000000e+00,False,degradation
3,Qwen3-4B,key_injection,standard,4096,2126,228,210,1532,-0.380224,1.000000e+00,False,degradation
4,Llama3-70B,dch_back,defense,4096,2014,27,225,1830,-39.330071,4.536286e-38,True,improvement
5,Llama3-70B,qi,standard,4096,2041,0,0,2055,0.000000,1.000000e+00,False,tie
6,Llama3-8B,dch_back_defense_n4096,unknown,4096,1438,1913,557,188,-172.211069,7.319446e-171,True,degradation
7,Llama3-8B,dch_back_standard_n4096,unknown,4096,486,3206,348,56,-1069.559575,0.000000e+00,True,degradation
8,Llama3-8B,qi,filter_qi,4096,3581,42,29,444,-0.812725,1.000000e+00,False,degradation
9,Llama3-8B,qi,standard,4096,3587,29,160,320,-22.421073,3.185708e-21,True,improvement
10,Qwen3-32B,qi_back,defense,4096,2781,450,164,701,-31.020166,8.878030e-30,True,degradation
11,Qwen3-32B,qi_back,defense_qi,4096,3710,163,75,148,-7.930045,7.048660e-07,True,degradation
12,Qwen3-32B,qi_back,standard,4096,2130,1437,121,408,-285.351105,5.925801e-284,True,degradation
13,Qwen3-4B,dch_back,defense,4096,3151,81,546,318,-84.906832,1.338418e-83,True,improvement
14,Qwen3-4B,doh_back,defense,4096,1322,1906,852,16,-90.957001,1.214484e-89,True,degradation
15,Qwen3-4B,doh_back,standard,4096,785,1569,1734,8,-2.364918,1.769564e-01,False,improvement
16,Qwen3-4B,qi_back,defense,4096,3128,103,292,573,-21.317789,3.944801e-20,True,improvement
17,Qwen3-4B,qi_back,filter_qi,4096,2334,20,8,1734,-1.447354,1.000000e+00,False,degradation
18,key_injection_Llama3-8B,20260922_152758,unknown,4096,3308,313,172,303,-9.812806,1.000247e-08,True,degradation
19,Llama3-70B,key_injection,defense,4096,2041,0,0,2055,0.000000,1.000000e+00,False,tie
20,GPT-OSS-20B,key_injection,defense,4096,3547,325,123,101,-21.378961,3.468307e-20,True,degradation
21,Llama-3-8B,key_injection,defense,4096,3474,281,130,211,-13.141236,5.056639e-12,True,degradation
22,Qwen3-32B,key_injection,defense,4096,2923,304,295,574,-0.128546,1.000000e+00,False,degradation
23,GPT-OSS-20B,key_injection,unknown,4096,3544,342,103,107,-30.290898,4.657393e-29,True,degradation
24,Llama3-70B,key_injection,unknown,4096,2041,0,0,2055,0.000000,1.000000e+00,False,tie
25,Qwen3-32B,key_injection,unknown,4096,3190,380,199,327,-13.334204,3.288928e-12,True,degradation

TREC-DL-2020 — Pointwise

,model,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Llama3-8B,qi,defense_qi,4096,2279,209,328,1280,-6.496821,1.879451e-05,True,improvement
1,Llama3-8B,qi,standard,4096,2535,269,369,923,-4.065197,4.475138e-03,True,improvement
2,Llama3-8B,sd,defense,4096,2029,558,17,1492,-140.518263,3.577826e-139,True,degradation
3,Llama3-8B,sd,standard,4096,1234,1570,0,1292,-472.316063,0.000000e+00,True,degradation
4,Llama3-8B,so,defense,4096,2226,361,88,1421,-39.581463,2.568995e-38,True,degradation
5,Llama3-8B,so,standard,4095,713,2090,6,1286,-630.657841,0.000000e+00,True,degradation
6,Qwen3-32B,sd,defense,3893,3634,6,75,178,-15.535963,2.154115e-14,True,improvement
7,Qwen3-32B,sd,standard,4094,561,3139,0,394,-944.632126,0.000000e+00,True,degradation
8,Qwen3-32B,so,defense,4079,3505,274,3,297,-76.534962,3.121918e-75,True,degradation
9,Qwen3-32B,so,standard,4091,2703,996,3,389,-292.207388,8.312210e-291,True,degradation
10,Qwen3-4B,sd,defense,307,49,8,0,250,-2.107210,2.890625e-01,False,degradation
11,Qwen3-4B,sd,standard,1050,364,318,0,368,-95.426509,4.157329e-94,True,degradation
12,Qwen3-4B,so,defense,316,55,11,1,249,-2.197387,2.412109e-01,False,degradation
13,Qwen3-4B,so,standard,1050,588,94,4,364,-22.623657,2.021910e-21,True,degradation
14,GPT-OSS-20B,key_injection,defense,4096,3077,732,30,257,-175.281903,6.322405e-174,True,degradation
15,GPT-OSS-20B,key_injection,standard,4096,3071,739,28,258,-179.498758,3.869026e-178,True,degradation
16,Qwen3-32B,key_injection,defense,4079,3005,770,18,286,-200.654185,2.793735e-199,True,degradation
17,Qwen3-32B,key_injection,standard,4095,2424,1283,10,378,-388.930754,0.000000e+00,True,degradation
18,Qwen3-4B,key_injection,defense,201,24,9,4,164,-0.573740,1.000000e+00,False,degradation
19,Qwen3-4B,key_injection,standard,900,493,89,21,297,-10.424215,2.522669e-09,True,degradation
20,Llama-3-8B,sd,defense,4093,2088,476,25,1504,-108.450778,4.002212e-107,True,degradation
21,Llama-3-8B,sd,standard,4089,1230,1540,0,1319,-463.285163,0.000000e+00,True,degradation
22,Llama-3-8B,so,defense,4090,2282,285,102,1421,-20.408955,3.158856e-19,True,degradation
23,Llama-3-8B,so,standard,4093,802,1971,4,1316,-594.233211,0.000000e+00,True,degradation
24,Llama3-70B,sd,defense,4096,3555,23,240,278,-46.010269,9.668647e-45,True,improvement
25,Llama3-70B,sd,standard,4096,63,3403,0,630,-1024.104045,0.000000e+00,True,degradation
26,Llama3-70B,so,defense,4096,3503,76,88,429,-0.408457,1.000000e+00,False,improvement
27,Llama3-70B,so,standard,460,91,352,1,16,-103.413555,4.321782e-102,True,degradation
28,GPT-OSS-20B,qi,defense_qi,4084,3731,56,44,253,-0.566625,1.000000e+00,False,degradation
29,GPT-OSS-20B,qi,standard,4092,3769,40,47,236,-0.283753,1.000000e+00,False,improvement
30,Llama-3-8B,qi,defense_qi,4094,2130,199,394,1371,-15.044456,6.589720e-14,True,improvement
31,Llama-3-8B,qi,standard,4096,2543,230,414,909,-12.412978,2.666069e-11,True,improvement
32,Llama3-70B,qi,defense_qi,4096,3357,151,168,420,-0.431364,1.000000e+00,False,improvement
33,Llama3-70B,qi,standard,4096,3309,154,228,405,-3.744986,8.814750e-03,True,improvement
34,Qwen3-32B,qi,defense_qi,3580,2922,116,37,505,-9.961494,7.211905e-09,True,degradation
35,Qwen3-32B,qi,standard,4048,3479,183,55,331,-16.527767,2.254479e-15,True,degradation

TREC-DL-2020 — Setwise

,model,attack,prompt,paired,both_correct,clean_correct_attack_wrong,clean_wrong_attack_correct,both_wrong,p_value_exact_log10,p_value_holm,significant_holm_0.05,direction
0,Qwen3-32B,qi_back,defense,3428,2184,143,154,947,-0.250408,1.000000,False,improvement
1,Qwen3-32B,key_injection,defense,3428,2127,200,137,964,-3.149478,0.032605,True,degradation

## Significant results

The log10 column remains informative when the ordinary floating-point p-value underflows to zero.

In [13]:
summary = display_df.copy()
summary['p_value'] = summary.apply(
    lambda row: f"10^({row['p_value_exact_log10']:.2f})"
    if row.get('p_value_exact', 1) == 0
    else f"{row['p_value_exact']:.3g}",
    axis=1,
)
summary = summary.rename(columns={
    'clean_correct_attack_wrong': 'b',
    'clean_wrong_attack_correct': 'c',
    'p_value_holm': 'Holm p',
})
summary[['model', 'dataset', 'paradigm', 'attack', 'prompt', 'paired', 'b', 'c', 'p_value', 'Holm p', 'significant_holm_0.05', 'direction']]

,model,dataset,paradigm,attack,prompt,paired,b,c,p_value,Holm p,significant_holm_0.05,direction
0,Llama3-70B,TREC-DL-2019,pairwise,dch,defense,4096,26,277,3.66e-54,3.699391e-52,True,improvement
1,Llama3-70B,TREC-DL-2019,pairwise,doh,standard,4096,2012,2029,0.801,1.000000e+00,False,improvement
2,Llama3-70B,TREC-DL-2020,pairwise,qi,defense_qi,4096,0,0,1,1.000000e+00,False,tie
3,Llama3-8B,TREC-DL-2019,pointwise,qi,defense_qi,4096,304,286,0.484,1.000000e+00,False,degradation
4,Llama3-8B,TREC-DL-2019,pointwise,qi,standard,4096,441,276,7.69e-10,4.921930e-08,True,degradation
...,...,...,...,...,...,...,...,...,...,...,...,...
130,Llama3-70B,TREC-DL-2020,pointwise,qi,standard,4096,154,228,0.00018,8.814750e-03,True,improvement
131,Qwen3-32B,TREC-DL-2019,pointwise,qi,defense_qi,3565,225,32,6.69e-37,6.352495e-35,True,degradation
132,Qwen3-32B,TREC-DL-2019,pointwise,qi,standard,4034,392,71,7.55e-55,7.697585e-53,True,degradation
133,Qwen3-32B,TREC-DL-2020,pointwise,qi,defense_qi,3580,116,37,1.09e-10,7.211905e-09,True,degradation
134,Qwen3-32B,TREC-DL-2020,pointwise,qi,standard,4048,183,55,2.97e-17,2.254479e-15,True,degradation

## Attack versus defense significance

This is a separate paired McNemar comparison: it compares the attacked predictions from the Default and Defense runs on the same instances. The p-values above compare clean versus attacked and answer a different question.

In [14]:
import json, math, re
from pathlib import Path
from collections import defaultdict

import sys
sys.path.insert(0, str(Path('Results')))
from mcnemar_all import _correct, _key, _metadata, _qrels, exact_mcnemar_p

def prompt_mcnemar(default_source, defense_source):
    default_path, defense_path = Path(default_source), Path(defense_source)
    meta = _metadata(defense_path)
    paradigm = meta['paradigm']
    qrels = None if paradigm == 'pointwise' else _qrels(f"msmarco-passage/trec-dl-{re.search(r'20\d\d', meta['dataset']).group()}")
    records = {}
    for path, name in ((default_path, 'default'), (defense_path, 'defense')):
        payload = json.loads(path.read_text(encoding='utf-8'))
        records[name] = {_key(r, paradigm): r for r in payload if isinstance(r, dict) and r.get('phase') == 'attacked' and _key(r, paradigm) is not None}
    a = b = c = d = 0
    for key in records['default'].keys() & records['defense'].keys():
        clean = _correct(records['default'][key], paradigm, qrels)
        defense = _correct(records['defense'][key], paradigm, qrels)
        if clean is None or defense is None: continue
        if clean and defense: a += 1
        elif clean and not defense: b += 1
        elif not clean and defense: c += 1
        else: d += 1
    return a, b, c, d, exact_mcnemar_p(b, c)

comparison_rows = []
for keys, group in results.groupby(['model', 'dataset', 'paradigm', 'attack']):
    sources = dict(zip(group['prompt'], group['source']))
    if 'Default' not in sources or 'Defense' not in sources: continue
    a, b, c, d, p = prompt_mcnemar(sources['Default'], sources['Defense'])
    comparison_rows.append(dict(zip(['model','dataset','paradigm','attack'], keys), paired=a+b+c+d, default_correct_defense_correct=a, default_correct_defense_wrong=b, default_wrong_defense_correct=c, default_wrong_defense_wrong=d, p_value_exact=p, direction='defense improves' if c > b else 'defense degrades' if b > c else 'tie'))

attack_vs_defense = pd.DataFrame(comparison_rows)
attack_vs_defense

Empty DataFrame
Columns: []
Index: []

## Attack-table-aligned defense test

Use `mcnemar_defense.py` for the attack-success comparison. This is the result to use when claiming that Defense changes attack success.

In [ ]:
defense_path = Path('Results/mcnemar_defense.csv')
if not defense_path.exists(): defense_path = Path('mcnemar_defense.csv')
attack_vs_defense = pd.read_csv(defense_path)
attack_vs_defense